---
title: "Food systems and Enviro Variability Review"
author: "Jessica Gephart"
date: "6/18/2019"
output: html_document
---

## Load packages
```{r, echo=FALSE}
library(tidyverse)
library(wosr)
library(ggplot2)
```

## 
```{r, echo=FALSE}
# Must have IP-based access to WOS API or login/password
SID <- auth(username = NULL, password = NULL)

# Break up request
years <- rep(2008:2019)
years <- sort(years)

search_p1 <- c('"climate varia*" OR "environment* varia*" OR "shock*" OR "propagat*" OR "weather" OR "extreme event*" OR "disaster*"')

search_p2<- c('"crop*" OR "livestock" OR "fish*" OR "food*"')

search_p3 <- c('"production" OR "nutrition*" OR "security" OR "diet*" OR "access" OR "availability" OR "system" OR "supply" OR "trade" OR "price transmission" OR "price volatility"')

search_p4 <- c('"food web*"')
           
queries <- paste("TS = (((", search_p1, ") AND (", search_p2, ") AND (", search_p3, ")) NOT (", search_p4, ")) AND PY = ", sep = "")

queries <- paste(queries, years, sep = "")

names(queries) <- (paste("search", 1:length(queries), sep = ""))

refs <- pull_wos_apply(queries, sid = SID)

saveRDS(refs, file = "refs_search6_28Jun19.rds")
```


```{r, echo=FALSE}
# Convert list to dataframe
df <- data.frame(publication = refs$publication)

write.csv(df, "food_variability_refs_28Jun19.csv", row.names = FALSE)
```

